image: julia:1-stretch

before_script:
  - julia --version
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_JULIA_VERSION

pages:
  stage: deploy
  script:
    - cp -r zh_CN/* ./
    - julia --project=doc --check-bounds=yes --color=yes -e 'include("doc/make.jl")'
    - mv doc/build public
  artifacts:
    paths:
      - public
