# DOC: https://gitlab.cn/docs/jh/ci/docker/using_docker_images.html
# 保持和 doc/Project.toml 中的版本一致
image: julia:1.10

before_script:
  - julia --version
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_REPO_SLUG
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_JULIA_VERSION

pages:
  stage: deploy
  script:
    - julia --project=doc --check-bounds=yes --color=yes -e 'include("doc/make.jl")'
    - mv doc/build public
  artifacts:
    paths:
      - public
